# CLIENT
steps:
  - name: "gcr.io/cloud-builders/yarn"
    args: ["install"]
    dir: "client"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - kms
      - decrypt
      - --key=cloudbuild-env
      - --keyring=audioly
      - --location=global
      - --plaintext-file=.env
      - --ciphertext-file=.env.enc
    dir: "client"
  - name: "gcr.io/cloud-builders/yarn"
    args: ["build"]
    dir: "client"
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "client.yaml"]
    dir: "client"

  # API
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    dir: "server"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - kms
      - decrypt
      - --key=cloudbuild-env
      - --keyring=audioly
      - --location=global
      - --plaintext-file=.env
      - --ciphertext-file=.env.enc
    dir: "server"
  - name: "gcr.io/cloud-builders/npm"
    args: ["build"]
    dir: "server"
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "api.yaml"]
    dir: "server"
options:
  logging: CLOUD_LOGGING_ONLY
timeout: "1600s"
